---
- name: Build and deploy Go application
  hosts: localhost  # ローカルでビルドを実行
  gather_facts: false

  tasks:
    - name: Build Go application
      command: go build -o isuride
      args:
        chdir: /workspaces/isucon14_observe/webapp/go  # ローカルのGoアプリケーションのディレクトリ
      register: build_result
      ignore_errors: no

    - name: Check if build was successful
      fail:
        msg: "Build failed. Check Go installation and code."
      when: build_result.rc != 0

    - name: Copy the webapp directory to the remote server
      delegate_to: server1  # デプロイ先のサーバー
      ansible.builtin.copy:
        src: /workspaces/isucon14_observe/webapp/go/isuride  # ローカルのwebappディレクトリ
        dest: /home/isucon/webapp/go/isuride  # 本番サーバのデプロイ先ディレクトリ
        mode: '0755'
        remote_src: no  # ローカルからリモートへコピー
      become: true  # root権限で実行

    - name: Copy the SQL schema file to the remote server
      delegate_to: server1  # デプロイ先のサーバー
      ansible.builtin.copy:
        src: /workspaces/isucon14_observe/webapp/sql/1-schema.sql  # ローカルのSQLスキーマファイル
        dest: /home/isucon/webapp/sql/1-schema.sql  # 本番サーバのデプロイ先ディレクトリ
        mode: '0644'
        remote_src: no  # ローカルからリモートへコピー
      become: true  # root権限で実行

- name: Restart the application on the remote server
  hosts: server1  # 本番サーバーでの操作
  become: true  # root権限で実行
  tasks:
    - name: Restart the application service
      ansible.builtin.systemd:
        name: isuride-go.service  # サービス名（適宜変更）
        state: restarted
      become: true